#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service
SERVICE_NAME="wordpress"

cat <<EOF

*******************************************************************************************
*                                                                                         *
*                    END OF LIFE NOTICE AUGUST 18, 2025                                   *
*                               tiredofit/wordpress                                       *
*                                                                                         *
* This image is no longer maintained as of and will not receive updates.                  *
*                                                                                         *
* A successor image is available at:                                                      *
*                                                                                         *
* Repository | Documentation:                                                             *
*   - https://github.com/nfrastack/container-wordpress                                    *
*                                                                                         *
* Image Registries:                                                                       *
*   - https://hub.docker.com/r/nfrastack/wordpress                                        *
*   - https://github.com/nfrastack/container-wordpress/pkgs/container/container-wordpress *
*                                                                                         *
* Please visit https://nfrastack.com for more information.                                *
*                                                                                         *
*******************************************************************************************

EOF

sleep 15


sanity_db mariadb
db_ready mariadb
sanity_var SITE_URL "Site URL"
bootstrap_filesystem
configure_wordpress
install_wordpress
create_bash_alias
finalize_permissions
print_info "Wordpress Initialization Complete, now starting webserver and PHP engine"

liftoff
