services:

  wordpress-app:
    image: docker.io/nfrastack/wordpress:latest
    container_name: wordpress-app
    labels:
      - traefik.enable=true
      - traefik.http.routers.wordpress.rule=Host(`wordpress.example.com`)
      - traefik.http.services.wordpress.loadbalancer.server.port=80
    links:
      - wordpress-db
    volumes:
      - ./data/:/www/wordpress
      - ./logs/:/www/logs
    environment:

      - CONTAINER_NAME=wordpress-app
      - DB_HOST=wordpress-db
      - DB_NAME=wordpress
      - DB_USER=wordpress
      - DB_PASS=userpassword

      - ENABLE_HTTPS_REVERSE_PROXY=FALSE

      - ADMIN_EMAIL=email@example.com
      - ADMIN_USER=admin
      - ADMIN_PASS=password
      - DEBUG_MODE=FALSE
    ### Enter this in as hostname.domain.tld or localhost if you are doing local development
      - SITE_URL=localhost
      - SITE_TITLE=Docker Wordpress
    ### This is next line is optional and only really used for local development - you would need to expose this port on your system to route to port 80
    ### If you are running a production system, get rid of thise environment variable entirely.
      #- SITE_PORT=8000

      - UPDATE_MODE=ALL
    networks:
      - proxy
      - services
    restart: always

  wordpress-db:
    image: docker.io/tiredofit/mariadb
    container_name: wordpress-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - ROOT_PASS=password
      - DB_NAME=wordpress
      - DB_USER=wordpress
      - DB_PASS=userpassword
    networks:
      - services
    restart: always

  wordpress-db-backup:
    container_name: wordpress-db-backup
    image: docker.io/tiredofit/db-backup
    links:
     - wordpress-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - DB01_HOST=wordpress-db
      - DB01_TYPE=mariadb
      - DB01_NAME=wordpress
      - DB01_USER=wordpress
      - DB01_PASS=userpassword
      - DB01_DUMP_FREQ=1440
      - DB01_DUMP_BEGIN=0000
      - DB01_CLEANUP_TIME=8640
    networks:
      - services
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true
