# Manual Workflow (Wordpress)

name: manual_build

on:
  workflow_dispatch:
    inputs:
      Manual Build:
        description: 'Manual Build'
        required: false
jobs:
  php56:
    uses: tiredofit/github_actions/.github/workflows/php56_alpine_amd64.yml@main
    secrets: inherit
  php70:
    uses: tiredofit/github_actions/.github/workflows/php70_alpine_amd64.yml@main
    secrets: inherit
  php71:
    uses: tiredofit/github_actions/.github/workflows/php71_alpine_amd64.yml@main
    secrets: inherit
  php72:
    uses: tiredofit/github_actions/.github/workflows/php72_alpine_amd64.yml@main
    secrets: inherit
  php73:
    uses: tiredofit/github_actions/.github/workflows/php73_alpine_amd64_armv7_arm64.yml@main
    secrets: inherit
  php74:
    uses: tiredofit/github_actions/.github/workflows/php74_alpine_amd64_armv7_arm64.yml@main
    secrets: inherit
  php80:
    uses: tiredofit/github_actions/.github/workflows/php80_alpine_amd64_armv7_arm64.yml@main
    secrets: inherit
  php81:
    uses: tiredofit/github_actions/.github/workflows/php81_alpine_amd64_armv7_arm64.yml@main
    secrets: inherit
  php82:
    uses: tiredofit/github_actions/.github/workflows/php82_alpine_amd64_armv7_arm64.yml@main
    secrets: inherit
  php83:
    uses: tiredofit/github_actions/.github/workflows/php83_alpine_amd64_armv7_arm64.yml@main
    secrets: inherit
